RealVideo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls')),
]
handler404 = 'video.views.notfound'

video/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .feeds import LatestPostFeed
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'video'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:pk>', views.movie, name='movie'),
    path('movie/<int:pk>/eval', views.movie_eval, name='movie_eval'),
    path('category/<str:c>', views.search_category, name='category'),
    path('tag/<str:t>', views.search_tag, name='tag'),
    path('search/', views.search_form, name='search'),
    path('contact/', views.page_contact, name='contact'),
    path('about/', views.page_about, name='about'),
    path('feed/', LatestPostFeed(), name='feed'),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

video/models.py
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.title

class Movie(models.Model):
    title = models.CharField(max_length=150)
    thumb = models.ImageField()
    iframe = models.TextField(null=True, blank=False)
    good = models.IntegerField(default=0)
    bad = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tag = models.TextField(blank=False)
    view = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    name = models.CharField(max_length=150)
    comment = models.TextField(null=False, blank=False)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

video/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

class SearchForm(forms.Form):
    squeeze = forms.CharField(required=True)

class CommentForm(forms.Form):
    name = forms.CharField(max_length=50, initial="名無し")
    comment = forms.CharField(required=True, widget=forms.Textarea())

class ContactForm(forms.Form):
    name = forms.CharField(label="お名前", required=True)
    email = forms.CharField(label="Email", required=True)
    subject = forms.CharField(label="件名", required=True)
    content = forms.CharField(label="内容", required=True, widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        subject = self.cleaned_data["subject"]
        content = self.cleaned_data["content"]
        to = "escape3new@icloud.com"

        send_mail(
            subject=subject,
            message="名前:" + name + "Email:" + email + "内容:" + content,
            from_email=email,
            recipient_list = [
                to,
            ]
        )

video/views.py
from django.shortcuts import get_object_or_404, redirect, render, render_to_response
import operator
from django.db.models import Q
from django.http import HttpResponse
from .models import *
from .forms import *
from django.http import Http404
from django.core.paginator import Paginator

def index(request):
    movies = Movie.objects.all().order_by('-created_at')
    paginator = Paginator(movies, 20)
    p = request.GET.get('p')
    movies = paginator.get_page(p)
    movies.paginator.all_page = range(movies.paginator.num_pages)
    for movie in movies:
        movie.tag = movie.tag.split(',')
    content = {
        'page_title': 'しこるおまとめ | ディルドオナニー、潮吹きなどの厳選した動画をまとめるエロサイト。',
        'search_form': SearchForm(),
        'movies': movies,
    }
    return render(request, 'video/index.html', content)

def movie(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            comment = form.cleaned_data['comment']
            movie = get_object_or_404(Movie, pk=pk)
            c = Comment(name=name, comment=comment, movie=movie)
            c.save()
        return redirect('video:movie', pk=pk)
    else:
        movie = get_object_or_404(Movie, pk=pk)
        movie.view += 1
        movie.save()
        comments = Comment.objects.filter(movie=movie).order_by('-created_at')
        queries = [Q(tag__icontains=tag) for tag in movie.tag.split(",")]
        query = queries.pop()
        for item in queries:
            query |= item
        movies = Movie.objects.filter(query)
        for rm in movies:
            rm.tag = rm.tag.split(',')
        content = {
            'page_title': 'しこるおまとめ | ' + movie.title,
            'search_form': SearchForm(),
            'comment_form': CommentForm(),
            'movie': movie,
            'relation': movies,
            'comments': comments,
        }
        return render(request, 'video/movie.html', content)

def movie_eval(request, pk):
    if request.method == 'POST':
        from django.http import QueryDict
        from json import dumps
        dic = QueryDict(request.body, encoding='utf-8')
        data = dic.get('eval')
        btn = get_object_or_404(Movie, pk=pk)
        if data == "good":
            btn.good += 1
            btn.save()
            cnt = btn.good
            return HttpResponse(dumps({"cnt": cnt}), content_type='application/json')
        elif data == "bad":
            btn.bad += 1
            btn.save()
            cnt = btn.bad
            return HttpResponse(dumps({"cnt": cnt}), content_type='application/json')
    return redirect('video:movie', pk=pk)
    
def search_category(request, c):
    category = get_object_or_404(Category, title=c)
    movies = Movie.objects.filter(category=category).order_by('-created_at')
    paginator = Paginator(movies, 20)
    p = request.GET.get('p')
    movies = paginator.get_page(p)
    movies.paginator.all_page = range(movies.paginator.num_pages)
    for movie in movies:
        movie.tag = movie.tag.split(',')
    content = {
        'page_title': 'しこるおまとめ | カテゴリ >> ' + c,
        'search_form': SearchForm(),
        'search_title': 'カテゴリ >> ' + c,
        'movies': movies,
    }
    return render(request, 'video/index.html', content)

def search_tag(request, t):
    movies = Movie.objects.filter(tag__icontains=t).order_by('-created_at')
    if len(movies) == 0: raise Http404
    paginator = Paginator(movies, 20)
    p = request.GET.get('p')
    movies = paginator.get_page(p)
    movies.paginator.all_page = range(movies.paginator.num_pages)
    for movie in movies:
        movie.tag = movie.tag.split(',')
    content = {
        'page_title': 'しこるおまとめ | タグ >> ' + t,
        'search_form': SearchForm(),
        'search_title': 'タグ >> ' + t,
        'movies': movies,
    }
    return render(request, 'video/index.html', content)

def search_form(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            txt = form.cleaned_data['squeeze']
            movies = Movie.objects.filter(title__icontains=txt).order_by('-created_at')
            if len(movies) == 0: raise Http404
            for movie in movies:
                movie.tag = movie.tag.split(',')
            content = {
                'page_title': 'しこるおまとめ | ディルドオナニー、潮吹きなどの厳選した動画をまとめるエロサイト。',
                'search_form': SearchForm(),
                'search_title': 'タイトル >> ' + txt,
                'movies': movies,
            }
            return render(request, 'video/index.html', content)
    return redirect('video:index')

def page_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        content = {
            "status": "正常に送信されませんでした",
            'page_title': 'しこるおまとめ | お問い合わせ',
            'search_form': SearchForm(),
            'contact_form': ContactForm(),
        }
        if form.is_valid():
            form.send_mail()
            content["status"] = "正常に送信されました"
        return render(request, 'video/contact.html', content)
    else:
        content = {
            'page_title': 'しこるおまとめ | お問い合わせ',
            'search_form': SearchForm(),
            'contact_form': ContactForm(),
        }
        return render(request, 'video/contact.html', content)

def page_about(request):
    content = {
        'page_title': 'しこるおまとめ | このサイトについて',
        'search_form': SearchForm(),
    }
    return render(request, 'video/about.html', content)

# 404
def notfound(request, exception):
    content = {
        'page_title': 'しこるおまとめ | 404 not found',
        'search_form': SearchForm(),
    }
    return render(request,'404.html', content)

video/templates/video/about.html
{% extends 'video/base.html' %}

{% block content %}
{% load static %}
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(90deg, rgba(40,139,243,1) 18%, rgba(84,201,238,1) 54%, rgba(135,236,194,1) 83%);">
    <div class="container desc">
        <h1 class="display-5 text-light">しこるおまとめについて</h1>
        <p class="lead text-light">しこるおまとめは無料で閲覧出来るアダルト動画のまとめサイトです。<br>アダルトコンテンツを含むため18歳未満の方は閲覧禁止です。</p>
    </div>
</div>
<section class="py-5">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <article class="desc">
                    <h3 class="text-primary icon"><i class="fas fa-user-lock"></i>サイトポリシー</h3>
                    <p>
                        当サイトはアダルト動画サイトをクロールしインデックスしているのであり著作権侵害、及びその助長を目的としてはおりません。<br>また動画共有サイトへのアップロード行為やそれを推奨、援助する行為は一切行っておりません。動画のご利用については各個人の責任でお願い致します。
                    </p>
                </article>
                <article class="desc">
                    <h3 class="text-primary icon"><i class="fas fa-video"></i>掲載されている動画について</h3>
                    <p>
                        当サイトは掲載している動画が著作権者の同意の元アップロードされているかを確認しておりません。掲載されている動画について問題などがございましたら各動画共有サイトへお問い合わせください。
                    </p>
                </article>
                <article class="desc">
                    <h3 class="text-primary icon"><i class="far fa-copyright"></i>著作権について</h3>
                    <p>
                        当サイトに掲載されている動画や画像の著作権は各権利所有者に帰属しております。問題がある場合は対象となるURLを明記の上、権利所有者ご本人様がご連絡下さい。確認後、早急に対応致します。
                    </p>
                </article>
                <article class="desc">
                    <h3 class="text-primary icon"><i class="far fa-comment"></i>免責事項</h3>
                    <p>
                        当サイト及び外部リンク先のサイトを利用したことにより発生したいかなる損失・損害についても当サイトは一切の責任と義務を負いません。ご利用は自己責任でお願い致します。
                    </p>
                </article>
                <div class="my-5 text-center">
                    <a class="btn btn-primary btn-lg" href="/contact" role="button">お問い合わせへ</a>
                </div>  
            </div>
        </div>
    </div>
</section>
{% endblock %}

video/templates/video/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="xvideos,pornhubなどから良質な動画を厳選したエロ動画まとめサイトです。毎日更新！！ディルドやバイブでのオナニー、潮吹きなどのオナニー動画が多め。あなたの性癖に刺さること間違いなし！！">
    <meta name="keywords" content="エロ動画,無料,アダルトまとめ,エロ動画まとめ,巨乳 エロ動画,お姉さん エロ動画 巨乳,オナニー,絶頂,キメセク,jc オナニー,jk オナニー,jd オナニー,女子大生　オナニー,オフパコ,jc リベンジポルノ,jk　リベンジポルノ,jd リベンジポルノ,バイブオナニー,ディルドオナニー">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ page_title }}</title>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% load widget_tweaks %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-152858239-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-152858239-1');
    </script>
</head>
<body>
<header class="bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex align-items-center justify-content-between">
                <!-- <h1 id="logo"><a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a></h1> -->
                <h1 id="site_title"><a href="/" class="d-block text-light" style="text-decoration: none;">しこるおまとめ</a></h1>
                <div>
                    <a id="search_btn" class="overlay_btn"><i class="fas fa-search open"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="overlay">
        <div class="container h-100">
            <div class="row h-100 position-relative">
                <a id="close_btn" class="overlay_btn"><i class="far fa-times-circle"></i></a>
                <div class="col-12 d-flex justify-content-center align-items-center">
                    <div class="content">
                        <h2 class="icon"><i class="fas fa-search"></i>検索</h2>
                        <p>キーワードで検索できます。</p>
                        <form action="{% url 'video:search' %}" method="post" class="form-inline justify-content-center">
                            {% csrf_token %}
                            {{ search_form.squeeze|add_class:"form-control w-50" }}
                            <span class="px-3"><input type="submit" value="検索" class="btn btn-primary"></span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
{% block content %}{% endblock %}
<footer class="bg-dark py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ul id="footer_menu">
                    <li><a href="/about">このサイトについて</a></li>
                    <li><a href="/contact">お問い合わせ</a></li>
                    <li><a href="{% url 'video:feed' %}"><i class="fas fa-rss pr-1"></i>RSS</a></li>
                </ul>
            </div>
        </div>
    </div>
<p class="copyright">Copyright 2019 (c) しこるおまとめ</p>
</footer>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

video/templates/video/contact.html
{% extends 'video/base.html' %}
{% load widget_tweaks %}
{% block content %}
{% load static %}
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(90deg, rgba(40,139,243,1) 18%, rgba(84,201,238,1) 54%, rgba(135,236,194,1) 83%);">
    <div class="container desc">
        <h1 class="display-5 text-light">しこるおまとめに広告を掲載しませんか？</h1>
        <p class="lead text-light">広告出稿のお申し込み、その他お問い合わせについては下記のお問い合わせフォームよりお願いします。<br>ご入力頂いた個人情報はお問い合わせ対応にのみ使用致します。</p>
    </div>
</div>
<section class="py-5">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                    {% if status %}
                        <div class="alert alert-success" role="alert"><strong>{{ status }}</strong></div>
                    {% endif %}
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-6"><img src="{% static 'img/ad.jpg' %}" class="mw-100" alt=""></div>
            <div class="col-md-6">
                <article class="desc pt-4 pt-md-0">
                    <h3 class="text-primary">広告掲載について</h3>
                    <p>
                        当サイトでは広告を随時募集しております。掲載位置や料金等クライアント様のご希望に柔軟に対応させて頂きます。<br>
                        ただしワンクリ等の違法サイトの広告はお断りさせて頂きますのでご了承ください。<br>
                        掲載を希望される方はページ下部のお問い合わせフォームよりご連絡ください。
                    </p>
                </article>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-6">
                <article>
                    <div class="table-responsive">
                    　　<table class="table table-condensed">
                        <thead>
                            <tr>
                                <th>デバイス</th>
                                <th>サイズ</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>PC</td>
                                <td>
                                    468×60<br>
                                    234×60<br>
                                    120×120<br>
                                    120×60<br>
                                    100×60<br>
                                </td>
                            </tr>
                            <tr>
                                <td>スマホ</td>
                                <td>
                                    320×50<br>
                                    480×32
                                </td>
                            </tr>
                        </tbody>
                    　　</table>
                    </div>
                </article>
            </div>
            <div class="col-md-6">
                <article class="desc pt-4">
                    <h3 class="text-primary">デバイス別の広告のサイズについて</h3>
                    <strong>PCの場合</strong>
                    <p>
                        PCサイトは、どんなバナーサイズでも掲載可能です。<br>
                        アクセストレードでは、左記5サイズがPCサイトでの掲載によく利用され、多くクリックされています。
                    </p>
                    <strong>スマホの場合</strong>
                    <p>
                        スマホサイトは、画面の縦・横にあわせた左記の2サイズが基本となります。最も使用されているのは、320×50です。
                    </p>
                </article>
            </div>
        </div>
    </div>
</section>
<section class="py-5" style="background: linear-gradient(90deg, rgba(83,146,213,1) 15%, rgba(82,100,157,1) 60%, rgba(37,75,82,1) 83%);">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="text-light pb-5 icon"><i class="far fa-envelope"></i>お問い合わせ</h2>
                <form action="{% url 'video:contact' %}" method="post" id="contact" class="form-block justify-content-center">
                    {% csrf_token %}
                    <label>{{ contact_form.name.label }}</label>
                    {{ contact_form.name|add_class:"form-control w-100 my-3" }}
                    <label>{{ contact_form.email.label }}</label>
                    {{ contact_form.email|add_class:"form-control w-100 my-3" }}
                    <label>{{ contact_form.subject.label }}</label>
                    {{ contact_form.subject|add_class:"form-control w-100 my-3" }}
                    <label>{{ contact_form.content.label }}</label>
                    {{ contact_form.content|add_class:"form-control w-100 my-3" }}
                    <span class="px-3 my-5 d-block text-center "><input type="submit" value="送信" class="btn btn-primary border-light"></span>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

video/templates/video/index.html
{% extends 'video/base.html' %}

{% block content %}
<div class="container">
<div class="row my-5">
    <div class="col-12"><h2 class="mb-5">{{ search_title }}</h2></div>
    {% for movie in movies %}
    <div class="mv_item col-6 col-md-3">
        <a href="{% url 'video:movie' movie.pk %}" class="mv_img">
            <img src="{{ movie.thumb.url }}">
        </a>
        <article>
            <h3>{{ movie.title }}</h3>
            <div>
                <ul class="eval_list">
                    <li><a><i class="far fa-hand-point-up"></i></a></li>
                    <li><span>{{ movie.good }}</span></li>
                    <li><a><i class="far fa-hand-point-down"></i></a></li>
                    <li><span>{{ movie.bad }}</span></li>
                </ul>
            </div>
            <a href="{% url 'video:category' movie.category.title %}" class="badge badge-danger">{{ movie.category }}</a>
            {% for tag in movie.tag %}
            <a href="{% url 'video:tag' tag %}" class="badge badge-primary">{{ tag }}</a>
            {% endfor %}
        </article>
    </div>
    {% endfor %}
    <div class="col-12 py-5">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if movies.has_previous %}
                <li class="page-item"><a class="page-link" href="?p={{ movies.previous_page_number }}">Prev</a></li>
                {% endif %}
                {% for page in movies.paginator.all_page %}
                    {% if movies.number == page|add:"1" %}
                    <li class="page-item active"><a class="page-link" href="?p={{ page|add:'1' }}">{{ page|add:"1" }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?p={{ page|add:'1' }}">{{ page|add:"1" }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if movies.has_next %}
                <li class="page-item"><a class="page-link" href="?p={{ movies.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
          </nav>
    </div>
    <div class="col-12 py-5">
        <div id="eroterest_partsv2" class="eroterest_partsv2"></div><script src="//bpm.eroterest.net/v2/?w=&e=&n=6&rn=4&spn=4&sprn=2&fc=&ts=&tp=&tbg=&tsz=&tr=&tc=&tmc=&tu=1&is=1&mts=&ds=&dsz=&dr=&dc=&df=&ibg=&ibm=&ids=&ib=&ibc=&ir=&sf="></script>
    </div>
</div>
</div>
{% endblock %}

video/templates/video/movie.html
{% extends 'video/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
<div class="row my-5">
    <div class="col-12">
        {% autoescape off %}
        {{ movie.iframe }}
        {% endautoescape %}
    </div>
    <div class="col-12">
        <h2 class="py-3">{{ movie.title }}</h2>
        <span id="pk" class="d-none">{{ movie.pk }}</span>
        <span>視聴回数: {{ movie.view }} 回</span>
        <ul class="eval_list">
            <li><a id="good"><i class="far fa-hand-point-up"></i></a></li>
            <li><span id="good_cnt">{{ movie.good }}</span></li>
            <li><a id="bad"><i class="far fa-hand-point-down"></i></a></li>
            <li><span id="bad_cnt">{{ movie.bad }}</span></li>
        </ul>
    </div>
    <div class="col-12">
        <h2 class="py-3 icon"><i class="fas fa-fire text-danger"></i>あなたへのおすすめ</h2>
    </div>
    {% for movie in relation %}
    <div class="mv_item col-6 col-md-3">
        <a href="{% url 'video:movie' movie.pk %}" class="mv_img">
            <img src="{{ movie.thumb.url }}">
        </a>
        <article>
            <h3>{{ movie.title }}</h3>
            <div>
                <ul class="eval_list">
                    <li><a><i class="far fa-hand-point-up"></i></a></li>
                    <li><span>{{ movie.good }}</span></li>
                    <li><a><i class="far fa-hand-point-down"></i></a></li>
                    <li><span>{{ movie.bad }}</span></li>
                </ul>
            </div>
            <a href="{% url 'video:category' movie.category.title %}" class="badge badge-danger">{{ movie.category }}</a>
            {% for tag in movie.tag %}
            <a href="{% url 'video:tag' tag %}" class="badge badge-primary">{{ tag }}</a>
            {% endfor %}
        </article>
    </div>
    {% endfor %}
    <div class="col-12 my-5">
            <div id="erKokOrigin" class="erKokOrigin"></div><script src="//kok.eroterest.net/origin/?da=&ma=&tag=&pch=&n=4&rn=&spn=4&sprn=&ms=&mw=&mw2=&mt=&mcl=&mbg=f8fcfc&mc=1d5959&msz=2&ts=&tt=&tcl=&tbg=&tsz=&tlh=&tc=&tmc=&tu=&lts=&ltt=&ltcl=&ltbg=&ltsz=&ltr=&ltlh=&ltc=&ltmc=&ltu=&ds=&dt=&dcl=&dsz=&dlh=&dc=&lds=&ldt=&ldcl=&ldsz=&ldr=&ldlh=&ldc=&ids=&idss=&ib=&ibs=&ibc=&ir=&irs=&ls=&lsbg=&lsc=&sf="></script>
    </div>
    <div class="col-12 my-5">
        {% if comments %}
            <h2 class="py-3 icon"><i class="far fa-comments text-info"></i>コメント一覧</h2>
        {% endif %}
        {% for comment in comments %}
            <p class="comment"><span class="badge badge-info">{{ comment.name }}</span><br>{{ comment.comment }}</p>
        {% endfor %}
    </div>
</div>
</div>
<section id="comment">
    <div class="container">
        <div class="row">
            <div class="col-12 py-5">
                <h2 class="py-3 icon"><i class="far fa-comment text-info"></i>コメントを書き込む</h2>
                <form action="{% url 'video:movie' movie.pk %}" method="post" class="form-block justify-content-center">
                    {% csrf_token %}
                    {{ comment_form.name|add_class:"form-control w-100 my-3" }}
                    {{ comment_form.comment|add_class:"form-control w-100 my-3" }}
                    <span class="px-3 my-5 d-block text-center "><input type="submit" value="コメントする" class="btn btn-primary"></span>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}